### ISSUE TITLE
Opening file causes crash

### ISSUE THREAD

**Issue by Amberlim** [Amberlim/Ambers-Dialog-System#2]
Editor crashes when you try to create a new file / open an old file if a file is ALREADY open.

**Comment by whytry313** [comment]
A lot of changes on the branch
Files changed:
- .gitignore: Ignores OS generated files (.gimport and .DS_Store)
- Option.gd, GraphNode.gd, Feature.gd: Delegate node destructions to its parent (Editor.gd)
- Editor.gd:
  - Stack based handling with node_stack: Name generation and node creation/destruction
  - Write-once code: creation of nodes now goes through the `get_new_node` method, same for `remove_node` that trigger `auto_connect_start` and node counts
  - Nodes bounds generation now happens on node creation - adds node to the right-bottom direction
  - async/await  fixes on open file event, this is to be removed as the signal is attached on `_ready` and needs to be attached via editor to keep consistency on the project

@Amberlim let me know if it needs some changes or it's good for a PR

EDIT: It turns out it's an engine error, the Graph doesn't wait for the frame to stop being busy, which leads to nodes not removed, which leads to node with the same name, which leads to later removed nodes and new ones that don't have the expected name. I ended up adding a 0.05sec timer but this could be fixed with a session ID passed at the end of the elements names (stripped on save and added on creation), hence not creating the naming conflict
