### ISSUE TITLE
JSON Dialog keys don't sort in numerical order

### ISSUE THREAD

**Issue by Amberlim** [Amberlim/Ambers-Dialog-System#5]
JSON has to be sorted manually as of now. 
If it's not sorted, it will crash when you open the file again in the editor.
To solve: 
Pad dialog keys/names with extra zeroes.
i.e. DIALOG_01 -> DIALOG_000001

**Comment by whytry313** [comment]
@Amberlim  I feel like I should provide more info about this fix
1. Create elements first, then config: Having a first loop that only creates elements avoid connections references errors, when `[NODE]_10` is treated first, it logically fails to link to `[NODE]_9` since it creates 1 to 8 first before being able to link, this could also happen with nodes like `[NODE]_1000` -> `[NODE]_4`, the fix makes sure the elements are created first before they can be linked
2. Data loss: when saved, the `node_data` data is stacked in the JSON file, on load this `node_data` wasn't restored, which make the node connected but the node itself (not the graph node) lose the `go to` property and in the same logic not being stored if the file is saved again
